language: php
php:
  - 5.4
  - 5.6
  - hhvm
  - 7.0
install:
- composer self-update --no-interaction
- composer update --no-interaction --prefer-dist
script:
- phpunit
env:
  global:
    secure: iYWazyvp/sBhqW4GMiOrPHXrUQTGVVNIPVTUU3mSvRmFSEvZRbL0NbfFEUJhfqNITrEoPxQxoDaf6MJ9UNPqfcARuChrUybHKFv9Ouvd05kmH4vwPJroJdl3iawQzeZBXpxg/Wn8ciW79bVuCH2/LMZWk1bcKS87VbjG6CwUF8s=
notifications:
  slack:
    secure: h9q+rtBdpa3O2uSgO07XiXoSV3wi77P8N6oFrr14ycnWx/j9CU/o0KqI1sR54p91/pwlSiPYBbN01m/J7Zgbf3mcAOTYiJNOQBmzPM0i1FKnvKaaZDmoWFByi6cwEgzd4f15CJWSwMv3bAQWpkBZ8gu+gCRAPquKDF6bWHiUYVU=
sudo: false
cache:
  directories:
    - vendor
    - $HOME/.composer/cache