language: php
matrix:
  include:
  - php: 5.4
  - php: 5.5
  - php: hhvm
install:
- composer self-update --no-interaction
- composer install --no-interaction --prefer-dist
script:
- composer run-script test
env:
  global:
    secure: iYWazyvp/sBhqW4GMiOrPHXrUQTGVVNIPVTUU3mSvRmFSEvZRbL0NbfFEUJhfqNITrEoPxQxoDaf6MJ9UNPqfcARuChrUybHKFv9Ouvd05kmH4vwPJroJdl3iawQzeZBXpxg/Wn8ciW79bVuCH2/LMZWk1bcKS87VbjG6CwUF8s=
notifications:
  slack:
    secure: h9q+rtBdpa3O2uSgO07XiXoSV3wi77P8N6oFrr14ycnWx/j9CU/o0KqI1sR54p91/pwlSiPYBbN01m/J7Zgbf3mcAOTYiJNOQBmzPM0i1FKnvKaaZDmoWFByi6cwEgzd4f15CJWSwMv3bAQWpkBZ8gu+gCRAPquKDF6bWHiUYVU=
